require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OnlineQuizGradesController do

  # This should return the minimal set of attributes required to create a valid
  # OnlineQuizGrade. As you add validations to OnlineQuizGrade, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OnlineQuizGradesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all online_quiz_grades as @online_quiz_grades" do
      online_quiz_grade = OnlineQuizGrade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:online_quiz_grades).should eq([online_quiz_grade])
    end
  end

  describe "GET show" do
    it "assigns the requested online_quiz_grade as @online_quiz_grade" do
      online_quiz_grade = OnlineQuizGrade.create! valid_attributes
      get :show, {:id => online_quiz_grade.to_param}, valid_session
      assigns(:online_quiz_grade).should eq(online_quiz_grade)
    end
  end

  describe "GET new" do
    it "assigns a new online_quiz_grade as @online_quiz_grade" do
      get :new, {}, valid_session
      assigns(:online_quiz_grade).should be_a_new(OnlineQuizGrade)
    end
  end

  describe "GET edit" do
    it "assigns the requested online_quiz_grade as @online_quiz_grade" do
      online_quiz_grade = OnlineQuizGrade.create! valid_attributes
      get :edit, {:id => online_quiz_grade.to_param}, valid_session
      assigns(:online_quiz_grade).should eq(online_quiz_grade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OnlineQuizGrade" do
        expect {
          post :create, {:online_quiz_grade => valid_attributes}, valid_session
        }.to change(OnlineQuizGrade, :count).by(1)
      end

      it "assigns a newly created online_quiz_grade as @online_quiz_grade" do
        post :create, {:online_quiz_grade => valid_attributes}, valid_session
        assigns(:online_quiz_grade).should be_a(OnlineQuizGrade)
        assigns(:online_quiz_grade).should be_persisted
      end

      it "redirects to the created online_quiz_grade" do
        post :create, {:online_quiz_grade => valid_attributes}, valid_session
        response.should redirect_to(OnlineQuizGrade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved online_quiz_grade as @online_quiz_grade" do
        # Trigger the behavior that occurs when invalid params are submitted
        OnlineQuizGrade.any_instance.stub(:save).and_return(false)
        post :create, {:online_quiz_grade => {}}, valid_session
        assigns(:online_quiz_grade).should be_a_new(OnlineQuizGrade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OnlineQuizGrade.any_instance.stub(:save).and_return(false)
        post :create, {:online_quiz_grade => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested online_quiz_grade" do
        online_quiz_grade = OnlineQuizGrade.create! valid_attributes
        # Assuming there are no other online_quiz_grades in the database, this
        # specifies that the OnlineQuizGrade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OnlineQuizGrade.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => online_quiz_grade.to_param, :online_quiz_grade => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested online_quiz_grade as @online_quiz_grade" do
        online_quiz_grade = OnlineQuizGrade.create! valid_attributes
        put :update, {:id => online_quiz_grade.to_param, :online_quiz_grade => valid_attributes}, valid_session
        assigns(:online_quiz_grade).should eq(online_quiz_grade)
      end

      it "redirects to the online_quiz_grade" do
        online_quiz_grade = OnlineQuizGrade.create! valid_attributes
        put :update, {:id => online_quiz_grade.to_param, :online_quiz_grade => valid_attributes}, valid_session
        response.should redirect_to(online_quiz_grade)
      end
    end

    describe "with invalid params" do
      it "assigns the online_quiz_grade as @online_quiz_grade" do
        online_quiz_grade = OnlineQuizGrade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OnlineQuizGrade.any_instance.stub(:save).and_return(false)
        put :update, {:id => online_quiz_grade.to_param, :online_quiz_grade => {}}, valid_session
        assigns(:online_quiz_grade).should eq(online_quiz_grade)
      end

      it "re-renders the 'edit' template" do
        online_quiz_grade = OnlineQuizGrade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OnlineQuizGrade.any_instance.stub(:save).and_return(false)
        put :update, {:id => online_quiz_grade.to_param, :online_quiz_grade => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested online_quiz_grade" do
      online_quiz_grade = OnlineQuizGrade.create! valid_attributes
      expect {
        delete :destroy, {:id => online_quiz_grade.to_param}, valid_session
      }.to change(OnlineQuizGrade, :count).by(-1)
    end

    it "redirects to the online_quiz_grades list" do
      online_quiz_grade = OnlineQuizGrade.create! valid_attributes
      delete :destroy, {:id => online_quiz_grade.to_param}, valid_session
      response.should redirect_to(online_quiz_grades_url)
    end
  end

end
