require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OnlineQuizzesController do

  # This should return the minimal set of attributes required to create a valid
  # OnlineQuiz. As you add validations to OnlineQuiz, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OnlineQuizzesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all online_quizzes as @online_quizzes" do
      online_quiz = OnlineQuiz.create! valid_attributes
      get :index, {}, valid_session
      assigns(:online_quizzes).should eq([online_quiz])
    end
  end

  describe "GET show" do
    it "assigns the requested online_quiz as @online_quiz" do
      online_quiz = OnlineQuiz.create! valid_attributes
      get :show, {:id => online_quiz.to_param}, valid_session
      assigns(:online_quiz).should eq(online_quiz)
    end
  end

  describe "GET new" do
    it "assigns a new online_quiz as @online_quiz" do
      get :new, {}, valid_session
      assigns(:online_quiz).should be_a_new(OnlineQuiz)
    end
  end

  describe "GET edit" do
    it "assigns the requested online_quiz as @online_quiz" do
      online_quiz = OnlineQuiz.create! valid_attributes
      get :edit, {:id => online_quiz.to_param}, valid_session
      assigns(:online_quiz).should eq(online_quiz)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OnlineQuiz" do
        expect {
          post :create, {:online_quiz => valid_attributes}, valid_session
        }.to change(OnlineQuiz, :count).by(1)
      end

      it "assigns a newly created online_quiz as @online_quiz" do
        post :create, {:online_quiz => valid_attributes}, valid_session
        assigns(:online_quiz).should be_a(OnlineQuiz)
        assigns(:online_quiz).should be_persisted
      end

      it "redirects to the created online_quiz" do
        post :create, {:online_quiz => valid_attributes}, valid_session
        response.should redirect_to(OnlineQuiz.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved online_quiz as @online_quiz" do
        # Trigger the behavior that occurs when invalid params are submitted
        OnlineQuiz.any_instance.stub(:save).and_return(false)
        post :create, {:online_quiz => {}}, valid_session
        assigns(:online_quiz).should be_a_new(OnlineQuiz)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OnlineQuiz.any_instance.stub(:save).and_return(false)
        post :create, {:online_quiz => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested online_quiz" do
        online_quiz = OnlineQuiz.create! valid_attributes
        # Assuming there are no other online_quizzes in the database, this
        # specifies that the OnlineQuiz created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OnlineQuiz.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => online_quiz.to_param, :online_quiz => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested online_quiz as @online_quiz" do
        online_quiz = OnlineQuiz.create! valid_attributes
        put :update, {:id => online_quiz.to_param, :online_quiz => valid_attributes}, valid_session
        assigns(:online_quiz).should eq(online_quiz)
      end

      it "redirects to the online_quiz" do
        online_quiz = OnlineQuiz.create! valid_attributes
        put :update, {:id => online_quiz.to_param, :online_quiz => valid_attributes}, valid_session
        response.should redirect_to(online_quiz)
      end
    end

    describe "with invalid params" do
      it "assigns the online_quiz as @online_quiz" do
        online_quiz = OnlineQuiz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OnlineQuiz.any_instance.stub(:save).and_return(false)
        put :update, {:id => online_quiz.to_param, :online_quiz => {}}, valid_session
        assigns(:online_quiz).should eq(online_quiz)
      end

      it "re-renders the 'edit' template" do
        online_quiz = OnlineQuiz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OnlineQuiz.any_instance.stub(:save).and_return(false)
        put :update, {:id => online_quiz.to_param, :online_quiz => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested online_quiz" do
      online_quiz = OnlineQuiz.create! valid_attributes
      expect {
        delete :destroy, {:id => online_quiz.to_param}, valid_session
      }.to change(OnlineQuiz, :count).by(-1)
    end

    it "redirects to the online_quizzes list" do
      online_quiz = OnlineQuiz.create! valid_attributes
      delete :destroy, {:id => online_quiz.to_param}, valid_session
      response.should redirect_to(online_quizzes_url)
    end
  end

end
